title: imberium
author: imberium

url: "https://imberium.github.io"
baseurl: "/"

footer_url: ""
footer_text: ""

profile-picture: assets/profile.jpg
cypriot-logo: assets/cypriot.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Blog"
   link: ""
 - name: "Projects"
   link: "projects"
 - name: "Publications"
   link: "publications" 
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
